ci(tmp): disable linux and snap in build_packages

diff --git a/.github/workflows/build_packages.yaml b/.github/workflows/build_packages.yaml
--- a/.github/workflows/build_packages.yaml
+++ b/.github/workflows/build_packages.yaml
@@ -144,195 +144,195 @@ jobs:
         ./emqx/bin/emqx ctl status
         ./emqx/bin/emqx stop || cat emqx/log/erlang.log.1
 
-  linux:
-    runs-on: ${{ github.repository_owner == 'emqx' && format('aws-ubuntu22.04-{0}', matrix.arch) || (matrix.arch == 'arm64' && 'ubuntu-22.04-arm' || 'ubuntu-22.04') }}
-    strategy:
-      fail-fast: false
-      matrix:
-        profile:
-          - ${{ inputs.profile }}
-        os:
-          - ubuntu24.04
-          - ubuntu22.04
-          - ubuntu20.04
-          - debian12
-          - debian11
-          - el9
-          - el8
-          - el7
-          - amzn2
-          - amzn2023
-        arch:
-          - amd64
-          - arm64
-        otp:
-          - ${{ inputs.otp_vsn }}
-        builder:
-          - ${{ inputs.builder_vsn }}
-        elixir:
-          - ${{ inputs.elixir_vsn }}
-        include:
-          - profile: ${{ inputs.profile }}
-            os: ubuntu22.04
-            arch: amd64
-            otp: ${{ inputs.otp_vsn }}
-            builder: ${{ inputs.builder_vsn }}
-            elixir: ${{ inputs.elixir_vsn }}
+  # linux:
+  #   runs-on: ${{ github.repository_owner == 'emqx' && format('aws-ubuntu22.04-{0}', matrix.arch) || (matrix.arch == 'arm64' && 'ubuntu-22.04-arm' || 'ubuntu-22.04') }}
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       profile:
+  #         - ${{ inputs.profile }}
+  #       os:
+  #         - ubuntu24.04
+  #         - ubuntu22.04
+  #         - ubuntu20.04
+  #         - debian12
+  #         - debian11
+  #         - el9
+  #         - el8
+  #         - el7
+  #         - amzn2
+  #         - amzn2023
+  #       arch:
+  #         - amd64
+  #         - arm64
+  #       otp:
+  #         - ${{ inputs.otp_vsn }}
+  #       builder:
+  #         - ${{ inputs.builder_vsn }}
+  #       elixir:
+  #         - ${{ inputs.elixir_vsn }}
+  #       include:
+  #         - profile: ${{ inputs.profile }}
+  #           os: ubuntu22.04
+  #           arch: amd64
+  #           otp: ${{ inputs.otp_vsn }}
+  #           builder: ${{ inputs.builder_vsn }}
+  #           elixir: ${{ inputs.elixir_vsn }}
 
-    defaults:
-      run:
-        shell: bash
+  #   defaults:
+  #     run:
+  #       shell: bash
 
-    steps:
-    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
-      with:
-        ref: ${{ github.event.inputs.ref }}
-        fetch-depth: 0
-    - name: build tgz
-      env:
-        PROFILE: ${{ matrix.profile }}
-        ARCH: ${{ matrix.arch }}
-        OS: ${{ matrix.os }}
-        BUILDER: "ghcr.io/emqx/emqx-builder/${{ matrix.builder }}:${{ matrix.elixir }}-${{ matrix.otp }}-${{ matrix.os }}"
-        BUILDER_SYSTEM: force_docker
-      run: |
-        ./scripts/buildx.sh \
-          --profile $PROFILE \
-          --arch $ARCH \
-          --builder $BUILDER \
-          --pkgtype tgz
-    - name: build pkg
-      env:
-        PROFILE: ${{ matrix.profile }}
-        ARCH: ${{ matrix.arch }}
-        OS: ${{ matrix.os }}
-        BUILDER: "ghcr.io/emqx/emqx-builder/${{ matrix.builder }}:${{ matrix.elixir }}-${{ matrix.otp }}-${{ matrix.os }}"
-        BUILDER_SYSTEM: force_docker
-      run: |
-        ./scripts/buildx.sh \
-          --profile $PROFILE \
-          --arch $ARCH \
-          --builder $BUILDER \
-          --pkgtype pkg
-    - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
-      with:
-        name: ${{ matrix.profile }}-${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.builder }}-${{ matrix.otp }}-${{ matrix.elixir }}
-        path: _packages/${{ matrix.profile }}/
-        retention-days: 7
+  #   steps:
+  #   - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+  #     with:
+  #       ref: ${{ github.event.inputs.ref }}
+  #       fetch-depth: 0
+  #   - name: build tgz
+  #     env:
+  #       PROFILE: ${{ matrix.profile }}
+  #       ARCH: ${{ matrix.arch }}
+  #       OS: ${{ matrix.os }}
+  #       BUILDER: "ghcr.io/emqx/emqx-builder/${{ matrix.builder }}:${{ matrix.elixir }}-${{ matrix.otp }}-${{ matrix.os }}"
+  #       BUILDER_SYSTEM: force_docker
+  #     run: |
+  #       ./scripts/buildx.sh \
+  #         --profile $PROFILE \
+  #         --arch $ARCH \
+  #         --builder $BUILDER \
+  #         --pkgtype tgz
+  #   - name: build pkg
+  #     env:
+  #       PROFILE: ${{ matrix.profile }}
+  #       ARCH: ${{ matrix.arch }}
+  #       OS: ${{ matrix.os }}
+  #       BUILDER: "ghcr.io/emqx/emqx-builder/${{ matrix.builder }}:${{ matrix.elixir }}-${{ matrix.otp }}-${{ matrix.os }}"
+  #       BUILDER_SYSTEM: force_docker
+  #     run: |
+  #       ./scripts/buildx.sh \
+  #         --profile $PROFILE \
+  #         --arch $ARCH \
+  #         --builder $BUILDER \
+  #         --pkgtype pkg
+  #   - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
+  #     with:
+  #       name: ${{ matrix.profile }}-${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.builder }}-${{ matrix.otp }}-${{ matrix.elixir }}
+  #       path: _packages/${{ matrix.profile }}/
+  #       retention-days: 7
 
-  snap:
-    runs-on: ${{ matrix.arch == 'arm64' && 'ubuntu-22.04-arm' || 'ubuntu-22.04' }}
-    strategy:
-      fail-fast: false
-      matrix:
-        profile:
-          - ${{ inputs.profile }}
-        arch:
-          - amd64
-          - arm64
+  # snap:
+  #   runs-on: ${{ matrix.arch == 'arm64' && 'ubuntu-22.04-arm' || 'ubuntu-22.04' }}
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       profile:
+  #         - ${{ inputs.profile }}
+  #       arch:
+  #         - amd64
+  #         - arm64
 
-    defaults:
-      run:
-        shell: bash
+  #   defaults:
+  #     run:
+  #       shell: bash
 
-    env:
-      PROFILE: ${{ matrix.profile }}
-      ARCH: ${{ matrix.arch }}
+  #   env:
+  #     PROFILE: ${{ matrix.profile }}
+  #     ARCH: ${{ matrix.arch }}
 
-    steps:
-    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
-      with:
-        ref: ${{ github.event.inputs.ref }}
-        fetch-depth: 0
+  #   steps:
+  #   - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+  #     with:
+  #       ref: ${{ github.event.inputs.ref }}
+  #       fetch-depth: 0
 
-    - name: Build tar.gz
-      env:
-        BUILDER: "ghcr.io/emqx/emqx-builder/${{ inputs.builder_vsn }}:${{ inputs.elixir_vsn }}-${{ inputs.otp_vsn }}-ubuntu22.04"
-        BUILDER_SYSTEM: force_docker
-        SNAP_BASE: core22
-      run: |
-        ./scripts/buildx.sh \
-          --profile $PROFILE \
-          --arch $ARCH \
-          --builder $BUILDER \
-          --pkgtype tgz
+  #   - name: Build tar.gz
+  #     env:
+  #       BUILDER: "ghcr.io/emqx/emqx-builder/${{ inputs.builder_vsn }}:${{ inputs.elixir_vsn }}-${{ inputs.otp_vsn }}-ubuntu22.04"
+  #       BUILDER_SYSTEM: force_docker
+  #       SNAP_BASE: core22
+  #     run: |
+  #       ./scripts/buildx.sh \
+  #         --profile $PROFILE \
+  #         --arch $ARCH \
+  #         --builder $BUILDER \
+  #         --pkgtype tgz
 
-        export EMQX_VERSION="$(./pkg-vsn.sh $PROFILE)"
-        export PACKAGE_SOURCE="_packages/${PROFILE}/${PROFILE}-${EMQX_VERSION}-ubuntu22.04-$ARCH.tar.gz"
-        # ensure package version length is capped at 32 characters (enforced by snap)
-        export EMQX_VERSION="${EMQX_VERSION:0:32}"
-        echo "EMQX_VERSION=$EMQX_VERSION" >> $GITHUB_ENV
-        echo "PACKAGE_SOURCE=$PACKAGE_SOURCE" >> $GITHUB_ENV
-        envsubst '${PROFILE},${EMQX_VERSION},${PACKAGE_SOURCE},${SNAP_BASE}' < deploy/snap/snapcraft.yaml > ./snapcraft.yaml
-        cat snapcraft.yaml
+  #       export EMQX_VERSION="$(./pkg-vsn.sh $PROFILE)"
+  #       export PACKAGE_SOURCE="_packages/${PROFILE}/${PROFILE}-${EMQX_VERSION}-ubuntu22.04-$ARCH.tar.gz"
+  #       # ensure package version length is capped at 32 characters (enforced by snap)
+  #       export EMQX_VERSION="${EMQX_VERSION:0:32}"
+  #       echo "EMQX_VERSION=$EMQX_VERSION" >> $GITHUB_ENV
+  #       echo "PACKAGE_SOURCE=$PACKAGE_SOURCE" >> $GITHUB_ENV
+  #       envsubst '${PROFILE},${EMQX_VERSION},${PACKAGE_SOURCE},${SNAP_BASE}' < deploy/snap/snapcraft.yaml > ./snapcraft.yaml
+  #       cat snapcraft.yaml
 
-    - name: Build snap
-      id: snapcraft
-      uses: snapcore/action-build@3bdaa03e1ba6bf59a65f84a751d943d549a54e79 # v1.3.0
+  #   - name: Build snap
+  #     id: snapcraft
+  #     uses: snapcore/action-build@3bdaa03e1ba6bf59a65f84a751d943d549a54e79 # v1.3.0
 
-    - name: Show logs if failed
-      if: failure()
-      run: |
-        cat ~/.local/state/snapcraft/log/*.log
+  #   - name: Show logs if failed
+  #     if: failure()
+  #     run: |
+  #       cat ~/.local/state/snapcraft/log/*.log
 
-    - name: Test snap
-      if: success()
-      run: |
-        sudo snap install "${{ steps.snapcraft.outputs.snap }}" --dangerous --devmode
-        # kill any process potentially running on emqx ports
-        for port in 1883 8883 8083 8084 18083; do
-          sudo fuser -k $port/tcp || true
-        done
-        sudo snap start "${PROFILE}"
-        for i in {1..30}; do
-          echo .
-          sudo snap logs "${PROFILE}" | grep -Eq "EMQX Enterprise ${EMQX_VERSION}.* is running now!" && break
-          sleep 1
-        done
-        if [ $i -eq 30 ]; then
-          sudo snap logs -n=all "${PROFILE}"
-          exit 1
-        fi
-        sudo snap remove "${PROFILE}"
+  #   - name: Test snap
+  #     if: success()
+  #     run: |
+  #       sudo snap install "${{ steps.snapcraft.outputs.snap }}" --dangerous --devmode
+  #       # kill any process potentially running on emqx ports
+  #       for port in 1883 8883 8083 8084 18083; do
+  #         sudo fuser -k $port/tcp || true
+  #       done
+  #       sudo snap start "${PROFILE}"
+  #       for i in {1..30}; do
+  #         echo .
+  #         sudo snap logs "${PROFILE}" | grep -Eq "EMQX Enterprise ${EMQX_VERSION}.* is running now!" && break
+  #         sleep 1
+  #       done
+  #       if [ $i -eq 30 ]; then
+  #         sudo snap logs -n=all "${PROFILE}"
+  #         exit 1
+  #       fi
+  #       sudo snap remove "${PROFILE}"
 
-    - name: Upload Snap as an artifact
-      if: success()
-      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
-      with:
-        name: "${{ matrix.profile }}-${{ matrix.arch }}-snap"
-        path: "${{ steps.snapcraft.outputs.snap }}"
+  #   - name: Upload Snap as an artifact
+  #     if: success()
+  #     uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
+  #     with:
+  #       name: "${{ matrix.profile }}-${{ matrix.arch }}-snap"
+  #       path: "${{ steps.snapcraft.outputs.snap }}"
 
-  publish_artifacts:
-    runs-on: ubuntu-latest
-    needs:
-      - mac
-      - test-mac
-      - linux
-      - snap
-    if: inputs.publish
-    strategy:
-      fail-fast: false
-      matrix:
-        profile:
-          - ${{ inputs.profile }}
-    steps:
-    - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
-      with:
-        pattern: "${{ matrix.profile }}-*"
-        path: packages/${{ matrix.profile }}
-        merge-multiple: true
-    - uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df # v4.2.1
-      with:
-        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
-    - name: upload to aws s3
-      env:
-        PROFILE: ${{ matrix.profile }}
-        REF_NAME: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.ref || github.ref_name }}
-        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
-        AWS_CLOUDFRONT_ID: ${{ secrets.AWS_CLOUDFRONT_ID }}
-      run: |
-        set -eu
-        aws s3 cp --recursive packages/$PROFILE s3://$AWS_S3_BUCKET/emqx-ee/$REF_NAME
-        aws cloudfront create-invalidation --distribution-id "$AWS_CLOUDFRONT_ID" --paths "/emqx-ee/$REF_NAME/*"
+  # publish_artifacts:
+  #   runs-on: ubuntu-latest
+  #   needs:
+  #     - mac
+  #     - test-mac
+  #     - linux
+  #     - snap
+  #   if: inputs.publish
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       profile:
+  #         - ${{ inputs.profile }}
+  #   steps:
+  #   - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
+  #     with:
+  #       pattern: "${{ matrix.profile }}-*"
+  #       path: packages/${{ matrix.profile }}
+  #       merge-multiple: true
+  #   - uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df # v4.2.1
+  #     with:
+  #       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+  #       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+  #       aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
+  #   - name: upload to aws s3
+  #     env:
+  #       PROFILE: ${{ matrix.profile }}
+  #       REF_NAME: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.ref || github.ref_name }}
+  #       AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
+  #       AWS_CLOUDFRONT_ID: ${{ secrets.AWS_CLOUDFRONT_ID }}
+  #     run: |
+  #       set -eu
+  #       aws s3 cp --recursive packages/$PROFILE s3://$AWS_S3_BUCKET/emqx-ee/$REF_NAME
+  #       aws cloudfront create-invalidation --distribution-id "$AWS_CLOUDFRONT_ID" --paths "/emqx-ee/$REF_NAME/*"
